apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  host: "microservices-demo-db.c742i0uge8r8.us-east-1.rds.amazonaws.com"
  username: "root"
  password: "postgres"
  database: "microservices"
